# -*- coding: utf-8 -*-
"""convercionLetras.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EPyRdwCgzddV22ech_QbWRYxQ5DXouBJ
"""

#Crear un programa que tome una cadena de texto cualquiera y transforme la primera letra de cada palabra
#en mayuscula sin usar funciones.

#Determinar que operaciones :
#Una cadena de resultado donde se guardara el resultado
#Una bandera que logica quw indique si la proxima letra debera convertirse en mayuscula

#Determinar conjuntos de datos:
#Palabras , y cantidad de letras de cada palabra
#Análisis a priori:
#La complejidad temporal depende linealmente del tamaño de la cadena, pues cada carácter se evalúa una sola vez.
def mayus_inicial(texto):
    resultado = ""
    i = 0
    while i < len(texto):
        if i == 0 or texto[i-1] == ' ':
            codigo = ord(texto[i])
            if codigo >= 97 and codigo <= 122:
                codigo -= 32
            resultado += chr(codigo)
        else:
            resultado += texto[i]
        i += 1
    return resultado

# Pedir texto al usuario
texto_usuario = input("Ingresa un texto: ")

# Mostrar texto convertido
print(mayus_inicial(texto_usuario))